### ISSUE TITLE
save meta regardless of dynamic plot as it contains latent space 

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#164] opened 2023-07-25 10:54 UTC

**Comment by marjanfamili** [comment] 2023-07-25 11:01
Or save latent space separately as the meta data contains the small figures it is approximately 40 Mb for 12000 input data and it is a quite large file to be saved repeatedly

**Comment by jolaem** [comment] 2023-08-08 12:23
Duplicate of #135

**Closed by jolaem** 2023-08-08 12:23 UTC
