### ISSUE TITLE
bug when vis_all : False

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#262] opened 2023-12-01 10:37 UTC
when only these visualisations are activated I get the following error : 

vis_emb:  true
vis_rec:  true
vis_los:  true
vis_int:  true
vis_dis:  true
vis_pos:  true

- Logging error ---
Traceback (most recent call last):
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/differentiable/../affinity-vae/run.py", line 667, in run
    run_pipeline(data)
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/differentiable/../affinity-vae/run.py", line 676, in run_pipeline
    train(
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/affinity-vae/avae/train.py", line 626, in train
    xs, ys, classes_list, epoch=epoch, writer=writer
UnboundLocalError: local variable 'classes_list' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bask/apps/live/EL8-ice/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/bask/apps/live/EL8-ice/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/bask/apps/live/EL8-ice/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/bask/apps/live/EL8-ice/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/differentiable/../affinity-vae/run.py", line 741, in <module>
    run()
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/pyenv_affinity/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/pyenv_affinity/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/pyenv_affinity/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/pyenv_affinity/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/differentiable/../affinity-vae/run.py", line 670, in run
    logging.exception("An exception was thrown!", e)
Message: 'An exception was thrown!'
Arguments: (UnboundLocalError("local variable 'classes_list' referenced before assignment"),)
--- Logging error ---
Traceback (most recent call last):
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/differentiable/../affinity-vae/run.py", line 667, in run
    run_pipeline(data)
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/differentiable/../affinity-vae/run.py", line 676, in run_pipeline
    train(
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/affinity-vae/avae/train.py", line 626, in train
    xs, ys, classes_list, epoch=epoch, writer=writer
UnboundLocalError: local variable 'classes_list' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bask/apps/live/EL8-ice/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/bask/apps/live/EL8-ice/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/bask/apps/live/EL8-ice/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/bask/apps/live/EL8-ice/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/differentiable/../affinity-vae/run.py", line 741, in <module>
    run()
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/pyenv_affinity/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/pyenv_affinity/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/pyenv_affinity/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/pyenv_affinity/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/differentiable/../affinity-vae/run.py", line 670, in run
    logging.exception("An exception was thrown!", e)
Message: 'An exception was thrown!'
Arguments: (UnboundLocalError("local variable 'classes_list' referenced before assignment"),)

It may be a bug I have created in my specific branch , I will investigate

**Comment by marjanfamili** [comment] 2023-12-01 10:38
It may be a bug I have created in my specific branch , I will investigate

**Comment by crangelsmith** [comment] 2023-12-01 11:01
i think this is related to issue #261

**Comment by jolaem** [comment] 2023-12-11 18:39
I think it's a duplicate of #261

**Comment by crangelsmith** [comment] 2024-04-24 09:25
This has been fixed.

**Closed by crangelsmith** 2024-04-24 09:25 UTC
